version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
     ACCEPT_EULA: Y
     MSSQL_PID: Standard
     SA_PASSWORD: Password123*
     MSSQL_AGENT_ENABLED: 'true'
    volumes:
      - ./mssql-server-linux:/var/opt/mssql/data

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
      - sqlserver
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    ports:
     - "9200:9200"
    environment:
     discovery.type: single-node
     xpack.security.enabled: 'false'
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  connector:
    image: debezium/connect:latest
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - zookeeper
      - sqlserver
      - kafka
      - elasticsearch